import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./componets/mainPages/NavBar";
import Footer from "./componets/mainPages/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mr.Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  }: Readonly<{
    children: React.ReactNode;
    }>) {
      return (
        <html lang="en">
      <body className={inter.className}>
      {/* <Navbar></Navbar> */}

        {children}
      {/* <Footer/> */}
        </body>
    </html>
  );
}
